import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { displayPrice } from './currency';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: typeof autoTable;
  }
}

interface DashboardStats {
  appointments: {
    total: number;
    today: number;
    pending: number;
    completed: number;
  };
  queue: {
    total: number;
    waiting: number;
    serving: number;
    avgWaitTime: number;
  };
  users?: {
    total: number;
    active: number;
    newThisMonth: number;
  };
  services?: {
    total: number;
    active: number;
  };
}

interface AIInsights {
  summary?: string;
  recommendations?: string[];
  predictions?: any;
}

interface Service {
  _id: string;
  name: string;
  price: number;
  duration: number;
  status: string;
  currency?: string;
}

export const generateInsightsPDF = async (
  stats: DashboardStats,
  insights: AIInsights,
  services: Service[],
  userName: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPos = 20;

  // Header with Logo/Title
  doc.setFillColor(79, 70, 229); // Primary color
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('SmartQ Analytics Report', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  doc.text(`Generated: ${currentDate}`, pageWidth / 2, 30, { align: 'center' });

  yPos = 50;
  doc.setTextColor(0, 0, 0);

  // Generated By
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text(`Generated by: ${userName}`, 14, yPos);
  yPos += 10;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(14, yPos, pageWidth - 14, yPos);
  yPos += 10;

  // System Overview Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('System Overview', 14, yPos);
  yPos += 10;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  // Appointments Stats
  const appointmentData = [
    ['Total Appointments', (stats.appointments?.total ?? 0).toString()],
    ['Today\'s Appointments', (stats.appointments?.today ?? 0).toString()],
    ['Pending', (stats.appointments?.pending ?? 0).toString()],
    ['Completed', (stats.appointments?.completed ?? 0).toString()],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['Appointments', 'Count']],
    body: appointmentData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], fontSize: 10, fontStyle: 'bold' },
    styles: { fontSize: 10 },
    margin: { left: 14, right: pageWidth / 2 + 7 },
  });

  // Queue Stats (side by side)
  const queueData = [
    ['Active Queues', (stats.queue?.total ?? 0).toString()],
    ['Waiting', (stats.queue?.waiting ?? 0).toString()],
    ['Currently Serving', (stats.queue?.serving ?? 0).toString()],
    ['Avg Wait Time', `${stats.queue?.avgWaitTime ?? 0} min`],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['Queue Status', 'Count']],
    body: queueData,
    theme: 'striped',
    headStyles: { fillColor: [16, 185, 129], fontSize: 10, fontStyle: 'bold' },
    styles: { fontSize: 10 },
    margin: { left: pageWidth / 2 + 7, right: 14 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Users & Services Stats (if available)
  if (stats.users && stats.services) {
    const systemData = [
      ['Total Users', (stats.users?.total ?? 0).toString()],
      ['Active Users', (stats.users?.active ?? 0).toString()],
      ['New This Month', (stats.users?.newThisMonth ?? 0).toString()],
      ['Total Services', (stats.services?.total ?? 0).toString()],
      ['Active Services', (stats.services?.active ?? 0).toString()],
    ];

    autoTable(doc, {
      startY: yPos,
      head: [['System Metrics', 'Value']],
      body: systemData,
      theme: 'grid',
      headStyles: { fillColor: [245, 158, 11], fontSize: 10, fontStyle: 'bold' },
      styles: { fontSize: 10 },
      margin: { left: 14, right: 14 },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  // Check if new page needed
  if (yPos > pageHeight - 60) {
    doc.addPage();
    yPos = 20;
  }

  // AI Insights Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229);
  doc.text('AI-Powered Insights', 14, yPos);
  yPos += 10;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  if (insights.summary) {
    doc.setFont('helvetica', 'bold');
    doc.text('Summary:', 14, yPos);
    yPos += 6;
    doc.setFont('helvetica', 'normal');
    
    const summaryLines = doc.splitTextToSize(insights.summary, pageWidth - 28);
    doc.text(summaryLines, 14, yPos);
    yPos += summaryLines.length * 5 + 8;
  }

  if (insights.recommendations && insights.recommendations.length > 0) {
    if (yPos > pageHeight - 60) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations:', 14, yPos);
    yPos += 6;
    doc.setFont('helvetica', 'normal');

    insights.recommendations.forEach((rec: string, index: number) => {
      if (yPos > pageHeight - 20) {
        doc.addPage();
        yPos = 20;
      }
      const recLines = doc.splitTextToSize(`${index + 1}. ${rec}`, pageWidth - 28);
      doc.text(recLines, 14, yPos);
      yPos += recLines.length * 5 + 4;
    });

    yPos += 5;
  }

  // Services Section
  if (services && services.length > 0) {
    if (yPos > pageHeight - 80) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text('Active Services', 14, yPos);
    yPos += 10;

    const serviceData = services.map(service => [
      service?.name || 'N/A',
      displayPrice(service?.price ?? 0, service?.currency),
      `${service?.duration ?? 0} min`,
      (service?.status || 'active').charAt(0).toUpperCase() + (service?.status || 'active').slice(1),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Service Name', 'Price', 'Duration', 'Status']],
      body: serviceData,
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229], fontSize: 10, fontStyle: 'bold' },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 35, halign: 'right' },
        2: { cellWidth: 30, halign: 'center' },
        3: { cellWidth: 30, halign: 'center' },
      },
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;
  }

  // Footer on last page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'SmartQ - Intelligent Queue Management System',
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );
  }

  // Download the PDF
  doc.save(`SmartQ-Analytics-Report-${new Date().toISOString().split('T')[0]}.pdf`);
};
